### ISSUE TITLE
\footnotelayout already used by paracol

### ISSUE THREAD

**Issue by ralessi** [FrankMittelbach/fmitex-footmisc#12]
`footmisc` cannot be used if `paracol` is loaded because both define the same `\footnotelayout` command.  Would it be possible to give this command another name in `footmisc`?

**Comment by ralessi** [comment]
> The `footmisc` package isway older than `paracol` and uses the command `\footnotelayot`for ages. Thus, it is not possible to change that without breaking a lot of existing documents. It would therefore be appropriate if `paracol` guards against that not the other way around.

Yes, I noticed that just after I opened this issue.

> I'll see if I can provide an alternative command in addition in a way that both packages can be used together, but it is not possible to simply rename it.

Thank you!  I wouldn't say how much trouble this is for the users of `paracol`, but at least some users of `ekdosis` (including myself) would appreciate the option of using both `ekdosis`, which loads `paracol`, and `footmisc`.  So wouldn't another way be to make `ekdosis` work with `footmisc`?  Do tell me if you think so, and I'll look into this.

**Comment by mgkurtz** [comment]
This is now solved in paracol by using the command name `\footnoteplacement` instead of `\footnotelayout`. If footmisc is not loaded, it will alias `\footnotelayout` to `\footnoteplacement` and if footmisc is loaded later, first `\footnotelayout` is set to `\relax`. So, either way, this incompatibility is solved.

**Comment by ralessi** [comment]
> This is now solved in paracol by using the command name `\footnoteplacement` instead of `\footnotelayout`. If footmisc is not loaded, it will alias `\footnotelayout` to `\footnoteplacement` and if footmisc is loaded later, first `\footnotelayout` is set to `\relax`. So, either way, this incompatibility is solved.

Yes, I've seen that change, thank you.

**Comment by FrankMittelbach** [comment]
thanks for the information, and sorry that despite promise I didn't find the time to look at it up to now, so good that this got resolved on the paracol side.
