### ISSUE TITLE
footmisc doesn't update \@currentcounter

### ISSUE THREAD

**Issue by u-fischer** [FrankMittelbach/fmitex-footmisc#15]
~~~~
\documentclass{article}
\usepackage{footmisc}
\begin{document}
\section{abc}
\RefProperty{fn:label}{counter}
abc\footnote{some text\RecordProperties{fn:label}{counter}}
\end{document}
~~~~

gives 

![image](https://github.com/user-attachments/assets/5dd2a0db-9405-4910-8244-fba4c719bd5e)

Without footmisc one gets the expected:

![image](https://github.com/user-attachments/assets/c6264589-94f8-499b-a124-16afd450732f)

This affects e.g. the cleveref firstaid ;-(.

In standard latex  `\@currentcounter` is set in `\@footnotetext` at the same place where `\@currentlabel` is set, but in footmisc this is missing.

**Comment by FrankMittelbach** [comment]
How is this output produced? I can't reproduce it. I mean, yes, the `\@currentcounter` is missing but I don't get this additional vertical bar

**Comment by u-fischer** [comment]
The vertical bar is the cursor, that sometimes happens in screenshots. Sorry for the confusion ;-)

**Comment by FrankMittelbach** [comment]
ah :-)

**Comment by FrankMittelbach** [comment]
uploaded to ctan
