### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by Rimole** [FrankMittelbach/fmitex-footmisc#17]
Documentation:

> However, whenever **_the_** is some infinite stretch at the end of the page, e.g., from using \newpage or \clearpage the footnotes are pushed to the bottom (in particular on the last page of a document or chapter).

the -> there, \clearpage -> comma after \clearpage
However, whenever **_there_** is some infinite stretch at the end of the page, e.g., from using \newpage or \clearpage, the footnotes are pushed to the bottom (in particular on the last page of a document or chapter).

> which **_nay_** have been modified by a

nay -> may
which **_may_*** have been modified by a

**Comment by FrankMittelbach** [comment]
thanks. Fixed in source, but it isn't worth making a new distribution (and generate extra work for the ctan folks)
