### ISSUE TITLE
Command \c@abspage already defined

### ISSUE THREAD

**Issue by martinantonmueller** [FrankMittelbach/fmitex-footmisc#2]
This MWE 
```
\documentclass{scrbook}
\usepackage[perpage]{footmisc} 
\usepackage[english]{babel}
\usepackage{zref-abspage}
\begin{document}
nothing much                                                      
\end{document}
```
creates the above stated message. Any idea how to avoid the options clash?

**Comment by FrankMittelbach** [comment]
The new footmisc implementation delegates the perpage option mainly to the package "perpage", so your conflict comes from zref-abspage not handling the fact that the counter "abspage" may already been defined, ie you get the same from
```
\documentclass{scrbook}
\usepackage{perpage}
\usepackage{zref-abspage}
```

Swappign the packages seems to work (though I'm not sure the two are really compatible). So with footmisc it means moving zref-abspage before footmisc.
