### ISSUE TITLE
Incorrect footnote number

### ISSUE THREAD

**Issue by kerkovits** [FrankMittelbach/fmitex-footmisc#3]
The following example:

    \documentclass{report}
    \usepackage[perpage]{footmisc}
    \begin{document}
    \chapter{Title}Test\footnote{text}
    \end{document}

Marks the footnote by number 2 instead of 1 under MikTEX.

![kép](https://user-images.githubusercontent.com/22369178/157032432-47d9b33c-686b-4f8a-ae1b-8b751bc27451.png)

**Comment by FrankMittelbach** [comment]
embarrassing :-( but as an excuse (not that it helps) it is caused by a package that is now loaded by footmisc, i.e. you get the same result if you just do
```
\usepackage{perpage}
\MakePerPage{footnote}
```
But as I said, doesn't help. This needs fixing asap.

**Comment by FrankMittelbach** [comment]
Try this as a workaround for now (after loading footmisc):
```
\makeatletter
  \def\@stpelt#1{\global\csname c@#1\endcsname \m@ne
    \stepcounter{#1}%
    \setcounter{#1}{0}%
  }

  \def\pp@cl@end@iii\stepcounter#1\setcounter#2#3{}
\makeatother
```
I'll see that I get an update to CTAN soon.

**Comment by FrankMittelbach** [comment]
An updated footmisc packages has reached CTAN (and as far as I can see also the TL distribution).

**Comment by kerkovits** [comment]
I manually updated the package from CTAN to 6.0d, and I confirm that the the bug is corrected. Thank you very much for your time.
