### ISSUE TITLE
footmisc: The `perpage` option will add two extra spaces at the end of the last paragraph

### ISSUE THREAD

**Issue by tanukihee** [FrankMittelbach/fmitex-footmisc#4]
MWE:
```LaTeX
\documentclass{article}
\usepackage[showframe]{geometry}
\usepackage[perpage]{footmisc}
\begin{document}
\hfill lorem

\hfill ipsum
\end{document}
```

Compiled by either pdflatex, xelatex or lualatex, we get
![image](https://user-images.githubusercontent.com/34062491/91831491-b8444780-ec76-11ea-81eb-ae2bc36d62c9.png)

I changed the length of `\spaceskip` and found there were two spaces added at the last;
I added a `%` at the end of the last paragraph and the spaces did not disappear;
I added one more new blank line before `\end{document}` and the spaces finally disappeared.

I also reported it to CTeX-org and they may have found the [reason](https://github.com/CTeX-org/forum/issues/144).

**Comment by FrankMittelbach** [comment]
not sure since when it is resolved, but it is resolved :-)
